let dogData = [
    {
        "tagName": "Maltese",
        "dogPic": "maltese.png",
        "country": "Malta, Southern Europe",
        "height": "20-25cm",
        "weight": "1,8-3,2 kg",
        "lifeSpan": "15-18 years",
        "contentTitle1": "Description",
        "contentText1": "The Maltese is a type of small dog known by various names, in Latin it is known as \"Canis Melitaeus\", whereas in English, one of them is also known as \"Bichon\". The Maltese ancestry originates from the Central Meditteranean Region. However, there is also evidence that the Maltese originated in Asia. Therefore, the true origin of the Maltese is still not known for certain. <br><br> The Maltese is an indulgent breed of dog, and wants love and attention. The Maltese tends to be active in homes and is more suspicious of small spaces for the Maltese, thus making him prefer closed spaces. Therefore, the Maltese is a breed of dog that is kept as a pet. In addition, Maltese people are very active and funny. But you still have to be supervised when playing with small children because there are some Maltese people who are sometimes impatient with small children. The Maltese experiences Separation Anxiety, so the Maltese companion must know this. <br><br> The Maltese dog has distinctive characteristics in its coat which is soft like silk, shiny, does not shed, long and smooth, white or pale ivory in color, and has straight or not wavy hair with a length of about 22 cm. In addition, the Maltese has a slightly rounded facial posture, has a slightly tapered muzzle, and has a dense body.",
        "contentTitle2": "Treatment",
        "contentText2": "The Maltese needs frequent cleaning to prevent the risk of tear stains around the Maltese's eyes. The way to clean Maltese tear stains is to use a fine-toothed metal comb moistened with warm water, and care should be taken to remove it through the hair on the muzzle just below the eyes. This cleaning should be done every two or three days, as the sticky layer rebuilds very quickly. In addition, the Maltese also needs regular grooming to prevent its coat from binding together, such as trimming the Maltese's fur. <br><br> For daily grooming of the Maltese, it is necessary to comb and brush the Maltese coat gently because the Maltese coat is very delicate, clean the eyes, and clean the beard after eating. Not only that, bathe the Maltese or use dry shampoo regularly and after that make sure the Maltese is completely dry. It is necessary to clean the ears and remove the hair that grows in the ears, and regularly trim the nails of the Maltese so as not to injure others or himself. If the Maltese suffers from excessive sneezing with audible characteristics such as a honking, grunting, or choking sound when playing, waking up, having an allergy, or when overexcited, the owner should take measures such as covering the Maltese's nostrils to force him to breathe through his mouth, as well should consult a doctor if something like this happens.",
        "contentTitle3": null,
        "contentText3": null
    },
    {
        "tagName": "Pomeranian",
        "dogPic": "pomeranian.png",
        "country": null,
        "height": null,
        "weight": null,
        "lifeSpan": null,
        "contentTitle1": null,
        "contentText1": null,
        "contentTitle2": null,
        "contentText2": null,
        "contentTitle3": null,
        "contentText3": null
    },
    {
        "tagName": "Poodle",
        "dogPic": "poodle.png",
        "country": null,
        "height": null,
        "weight": null,
        "lifeSpan": null,
        "contentTitle1": null,
        "contentText1": null,
        "contentTitle2": null,
        "contentText2": null,
        "contentTitle3": null,
        "contentText3": null
    },
    {
        "tagName": "Dobermann",
        "dogPic": "dobermann.png",
        "country": null,
        "height": null,
        "weight": null,
        "lifeSpan": null,
        "contentTitle1": null,
        "contentText1": null,
        "contentTitle2": null,
        "contentText2": null,
        "contentTitle3": null,
        "contentText3": null
    },
    {
        "tagName": "Pekingese",
        "dogPic": "pekingese.png",
        "country": null,
        "height": null,
        "weight": null,
        "lifeSpan": null,
        "contentTitle1": null,
        "contentText1": null,
        "contentTitle2": null,
        "contentText2": null,
        "contentTitle3": null,
        "contentText3": null
    },
    {
        "tagName": "Shih Tzu",
        "dogPic": "shih-tzu.png",
        "country": null,
        "height": null,
        "weight": null,
        "lifeSpan": null,
        "contentTitle1": null,
        "contentText1": null,
        "contentTitle2": null,
        "contentText2": null,
        "contentTitle3": null,
        "contentText3": null
    },
    {
        "tagName": "Yorkshire Terrier",
        "dogPic": "yorkshire-terrier.png",
        "country": null,
        "height": null,
        "weight": null,
        "lifeSpan": null,
        "contentTitle1": null,
        "contentText1": null,
        "contentTitle2": null,
        "contentText2": null,
        "contentTitle3": null,
        "contentText3": null
    },
    {
        "tagName": "Border Collie",
        "dogPic": "border-collie.png",
        "country": null,
        "height": null,
        "weight": null,
        "lifeSpan": null,
        "contentTitle1": null,
        "contentText1": null,
        "contentTitle2": null,
        "contentText2": null,
        "contentTitle3": null,
        "contentText3": null
    },
    {
        "tagName": "Chihuahua",
        "dogPic": "chihuahua.png",
        "country": null,
        "height": null,
        "weight": null,
        "lifeSpan": null,
        "contentTitle1": null,
        "contentText1": null,
        "contentTitle2": null,
        "contentText2": null,
        "contentTitle3": null,
        "contentText3": null
    },
    {
        "tagName": "Beagle",
        "dogPic": "beagle.png",
        "country": null,
        "height": null,
        "weight": null,
        "lifeSpan": null,
        "contentTitle1": null,
        "contentText1": null,
        "contentTitle2": null,
        "contentText2": null,
        "contentTitle3": null,
        "contentText3": null
    },
    {
        "tagName": "Kintamani",
        "dogPic": "kintamani.png",
        "country": null,
        "height": null,
        "weight": null,
        "lifeSpan": null,
        "contentTitle1": null,
        "contentText1": null,
        "contentTitle2": null,
        "contentText2": null,
        "contentTitle3": null,
        "contentText3": null
    },
    {
        "tagName": "Bulldog",
        "dogPic": "bulldog.png",
        "country": null,
        "height": null,
        "weight": null,
        "lifeSpan": null,
        "contentTitle1": null,
        "contentText1": null,
        "contentTitle2": null,
        "contentText2": null,
        "contentTitle3": null,
        "contentText3": null
    },
    {
        "tagName": "Akita Inu",
        "dogPic": "akita-inu.png",
        "country": null,
        "height": null,
        "weight": null,
        "lifeSpan": null,
        "contentTitle1": null,
        "contentText1": null,
        "contentTitle2": null,
        "contentText2": null,
        "contentTitle3": null,
        "contentText3": null
    },
    {
        "tagName": "Golden Retriever",
        "dogPic": "golden-retriever.png",
        "country": null,
        "height": null,
        "weight": null,
        "lifeSpan": null,
        "contentTitle1": null,
        "contentText1": null,
        "contentTitle2": null,
        "contentText2": null,
        "contentTitle3": null,
        "contentText3": null
    },
    {
        "tagName": "Pug",
        "dogPic": "pug.png",
        "country": null,
        "height": null,
        "weight": null,
        "lifeSpan": null,
        "contentTitle1": null,
        "contentText1": null,
        "contentTitle2": null,
        "contentText2": null,
        "contentTitle3": null,
        "contentText3": null
    },
    {
        "tagName": "Corgi",
        "dogPic": "corgi.png",
        "country": null,
        "height": null,
        "weight": null,
        "lifeSpan": null,
        "contentTitle1": null,
        "contentText1": null,
        "contentTitle2": null,
        "contentText2": null,
        "contentTitle3": null,
        "contentText3": null
    },
    {
        "tagName": "Shiba Inu",
        "dogPic": "shiba-inu.png",
        "country": null,
        "height": null,
        "weight": null,
        "lifeSpan": null,
        "contentTitle1": null,
        "contentText1": null,
        "contentTitle2": null,
        "contentText2": null,
        "contentTitle3": null,
        "contentText3": null
    },
    {
        "tagName": "Alaskan Malamute",
        "dogPic": "alaskan-malamute.png",
        "country": null,
        "height": null,
        "weight": null,
        "lifeSpan": null,
        "contentTitle1": null,
        "contentText1": null,
        "contentTitle2": null,
        "contentText2": null,
        "contentTitle3": null,
        "contentText3": null
    },
    {
        "tagName": "Pitbull",
        "dogPic": "pitbull.png",
        "country": null,
        "height": null,
        "weight": null,
        "lifeSpan": null,
        "contentTitle1": null,
        "contentText1": null,
        "contentTitle2": null,
        "contentText2": null,
        "contentTitle3": null,
        "contentText3": null
    },
    {
        "tagName": "Dalmatian",
        "dogPic": "dalmatian.png",
        "country": null,
        "height": null,
        "weight": null,
        "lifeSpan": null,
        "contentTitle1": null,
        "contentText1": null,
        "contentTitle2": null,
        "contentText2": null,
        "contentTitle3": null,
        "contentText3": null
    }
]

let container = document.getElementById("dogListContainer");
for (var i = 0; i < dogData.length; i++) {
    container.innerHTML += `<a href="dog_wiki.html?${i}" class="dogList">
    <img class="dogPhoto" src="img/${dogData[i].dogPic}">
    <p class="dogName">${dogData[i].tagName}</p>
</a>`
}